<?php

/**
 * Admin panel module registry — maps route slugs to MySQL models and UI config.
 * Controllers use ProvidesMySqlCrud + moduleSlug().
 */
return [
    'sections' => [
        'model' => \App\Models\Section::class,
        'label' => 'Sections',
        'permission' => 'section',
        'searchable' => ['name', 'serviceType'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'serviceType', 'label' => 'Service Type'],
            ['field' => 'isActive', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'serviceType', 'type' => 'text', 'label' => 'Service Type'],
            ['name' => 'isActive', 'type' => 'checkbox', 'label' => 'Active'],
            ['name' => 'sectionImage', 'type' => 'image', 'label' => 'Image'],
            ['name' => 'color', 'type' => 'text', 'label' => 'Color'],
            ['name' => 'nearByRadius', 'type' => 'number', 'label' => 'Nearby Radius'],
            ['name' => 'delivery_charge', 'type' => 'number', 'label' => 'Delivery Charge'],
        ],
    ],
    'taxes' => [
        'model' => \App\Models\Tax::class,
        'route' => 'tax',
        'label' => 'Taxes',
        'permission' => 'tax',
        'searchable' => ['title', 'country', 'type'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'country', 'label' => 'Country'],
            ['field' => 'type', 'label' => 'Type'],
            ['field' => 'enable', 'label' => 'Status', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'country', 'type' => 'text', 'label' => 'Country'],
            ['name' => 'type', 'type' => 'text', 'label' => 'Type'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'enable', 'type' => 'checkbox', 'label' => 'Enabled'],
        ],
    ],
    'currencies' => [
        'model' => \App\Models\Currency::class,
        'label' => 'Currencies',
        'permission' => 'currency',
        'searchable' => ['name', 'code', 'country'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'code', 'label' => 'Code'],
            ['field' => 'symbol', 'label' => 'Symbol'],
            ['field' => 'isActive', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'code', 'type' => 'text', 'label' => 'Code', 'required' => true],
            ['name' => 'symbol', 'type' => 'text', 'label' => 'Symbol'],
            ['name' => 'country', 'type' => 'text', 'label' => 'Country'],
            ['name' => 'isActive', 'type' => 'checkbox', 'label' => 'Active'],
            ['name' => 'symbolAtRight', 'type' => 'checkbox', 'label' => 'Symbol At Right'],
            ['name' => 'decimal_degits', 'type' => 'number', 'label' => 'Decimal Digits'],
        ],
    ],
    'brands' => [
        'model' => \App\Models\Brand::class,
        'label' => 'Brands',
        'permission' => 'brands',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'sectionId', 'label' => 'Section'],
            ['field' => 'is_publish', 'label' => 'Published', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'photo', 'type' => 'image', 'label' => 'Photo'],
            ['name' => 'is_publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'vendor-categories' => [
        'model' => \App\Models\VendorCategory::class,
        'view' => 'vendor_categories',
        'route' => 'categories',
        'label' => 'Categories',
        'permission' => 'category',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'section_id', 'label' => 'Section'],
            ['field' => 'publish', 'label' => 'Published', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'description', 'type' => 'textarea', 'label' => 'Description'],
            ['name' => 'section_id', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'photo', 'type' => 'image', 'label' => 'Photo'],
            ['name' => 'publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'vendor-filters' => [
        'model' => \App\Models\VendorFilter::class,
        'view' => 'vendor_filters',
        'route' => 'vendor-filters',
        'label' => 'Vendor Filters',
        'permission' => 'vendor-filters',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'options', 'type' => 'json', 'label' => 'Options (JSON array)'],
        ],
    ],
    'vendor-attributes' => [
        'model' => \App\Models\VendorAttribute::class,
        'view' => 'vendor_attributes',
        'route' => 'attributes',
        'label' => 'Attributes',
        'permission' => 'item-attribute',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
        ],
    ],
    'documents' => [
        'model' => \App\Models\Document::class,
        'label' => 'Documents',
        'permission' => 'documents',
        'searchable' => ['title', 'type'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'type', 'label' => 'Type'],
            ['field' => 'enable', 'label' => 'Enabled', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'type', 'type' => 'select', 'label' => 'Type', 'options' => ['vendor' => 'Vendor', 'driver' => 'Driver', 'owner' => 'Owner']],
            ['name' => 'frontSide', 'type' => 'checkbox', 'label' => 'Front Side'],
            ['name' => 'backSide', 'type' => 'checkbox', 'label' => 'Back Side'],
            ['name' => 'enable', 'type' => 'checkbox', 'label' => 'Enabled'],
        ],
    ],
    'review-attributes' => [
        'model' => \App\Models\ReviewAttribute::class,
        'view' => 'review_attributes',
        'route' => 'review-attributes',
        'label' => 'Review Attributes',
        'permission' => 'review-attribute',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
        ],
    ],
    'coupons' => [
        'model' => \App\Models\Coupon::class,
        'label' => 'Coupons',
        'permission' => 'coupons',
        'searchable' => ['code'],
        'columns' => [
            ['field' => 'code', 'label' => 'Code'],
            ['field' => 'discount', 'label' => 'Discount'],
            ['field' => 'vendorID', 'label' => 'Vendor'],
        ],
        'form' => [
            ['name' => 'code', 'type' => 'text', 'label' => 'Code', 'required' => true],
            ['name' => 'discount', 'type' => 'number', 'label' => 'Discount'],
            ['name' => 'discountType', 'type' => 'text', 'label' => 'Discount Type'],
            ['name' => 'vendorID', 'type' => 'text', 'label' => 'Vendor ID'],
            ['name' => 'section_id', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'expiresAt', 'type' => 'datetime', 'label' => 'Expires At'],
            ['name' => 'image', 'type' => 'image', 'label' => 'Image'],
        ],
    ],
    'subscription-plans' => [
        'model' => \App\Models\SubscriptionPlan::class,
        'view' => 'subscription_plans',
        'route' => 'subscription-plans',
        'label' => 'Subscription Plans',
        'permission' => 'subscription-plans',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'price', 'label' => 'Price'],
            ['field' => 'isEnable', 'label' => 'Enabled', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'price', 'type' => 'number', 'label' => 'Price'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'isEnable', 'type' => 'checkbox', 'label' => 'Enabled'],
        ],
    ],
    'vehicle-types' => [
        'model' => \App\Models\VehicleType::class,
        'view' => 'vehicle_types',
        'route' => 'vehicle-types',
        'label' => 'Vehicle Types',
        'permission' => 'vehicle-type',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'sectionId', 'label' => 'Section'],
            ['field' => 'isActive', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'capacity', 'type' => 'number', 'label' => 'Capacity'],
            ['name' => 'isActive', 'type' => 'checkbox', 'label' => 'Active'],
        ],
    ],
    'rental-vehicle-types' => [
        'model' => \App\Models\RentalVehicleType::class,
        'view' => 'rental_vehicle_types',
        'route' => 'rental-vehicle-types',
        'label' => 'Rental Vehicle Types',
        'permission' => 'rental-vehicle-type',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'sectionId', 'label' => 'Section'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'capacity', 'type' => 'number', 'label' => 'Capacity'],
            ['name' => 'isActive', 'type' => 'checkbox', 'label' => 'Active'],
        ],
    ],
    'rental-packages' => [
        'model' => \App\Models\RentalPackage::class,
        'view' => 'rental_packages',
        'route' => 'rental-packages',
        'label' => 'Rental Packages',
        'permission' => 'rental-package',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'baseFare', 'label' => 'Base Fare'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'baseFare', 'type' => 'number', 'label' => 'Base Fare'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'vehicleTypeId', 'type' => 'text', 'label' => 'Vehicle Type ID'],
        ],
    ],
    'parcel-categories' => [
        'model' => \App\Models\ParcelCategory::class,
        'view' => 'parcel_categories',
        'route' => 'parcel-categories',
        'label' => 'Parcel Categories',
        'permission' => 'parcel-category',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'sectionId', 'label' => 'Section'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'image', 'type' => 'image', 'label' => 'Image'],
            ['name' => 'publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'parcel-weights' => [
        'model' => \App\Models\ParcelWeight::class,
        'view' => 'parcel_weights',
        'route' => 'parcel-weights',
        'label' => 'Parcel Weights',
        'permission' => 'parcel-weight',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'delivery_charge', 'label' => 'Delivery Charge'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'delivery_charge', 'type' => 'number', 'label' => 'Delivery Charge'],
        ],
    ],
    'gift-cards' => [
        'model' => \App\Models\GiftCard::class,
        'view' => 'gift_cards',
        'route' => 'gift-cards',
        'label' => 'Gift Cards',
        'permission' => 'gift-card',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'isEnable', 'label' => 'Enabled', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'image', 'type' => 'image', 'label' => 'Image'],
            ['name' => 'expiryDay', 'type' => 'number', 'label' => 'Expiry Days'],
            ['name' => 'isEnable', 'type' => 'checkbox', 'label' => 'Enabled'],
        ],
    ],
    'cms-pages' => [
        'model' => \App\Models\CmsPage::class,
        'view' => 'cms_pages',
        'route' => 'cms-pages',
        'label' => 'CMS Pages',
        'permission' => 'cms',
        'searchable' => ['name', 'slug'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'slug', 'label' => 'Slug'],
            ['field' => 'publish', 'label' => 'Published', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'slug', 'type' => 'text', 'label' => 'Slug'],
            ['name' => 'description', 'type' => 'textarea', 'label' => 'Content'],
            ['name' => 'publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'on-boarding' => [
        'model' => \App\Models\OnBoarding::class,
        'view' => 'on_boarding',
        'route' => 'on-boarding',
        'label' => 'Onboarding',
        'permission' => 'on-boarding',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'type', 'label' => 'Type'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'description', 'type' => 'textarea', 'label' => 'Description'],
            ['name' => 'image', 'type' => 'image', 'label' => 'Image'],
            ['name' => 'type', 'type' => 'text', 'label' => 'Type'],
        ],
    ],
    'popular-destinations' => [
        'model' => \App\Models\PopularDestination::class,
        'view' => 'popular_destinations',
        'route' => 'popular-destinations',
        'label' => 'Popular Destinations',
        'permission' => 'popular-destination',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'sectionId', 'label' => 'Section'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'latitude', 'type' => 'number', 'label' => 'Latitude'],
            ['name' => 'longitude', 'type' => 'number', 'label' => 'Longitude'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'image', 'type' => 'image', 'label' => 'Image'],
        ],
    ],
    'banner-items' => [
        'model' => \App\Models\BannerItem::class,
        'view' => 'banner_items',
        'route' => 'banners',
        'label' => 'Banners',
        'permission' => 'banner',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'sectionId', 'label' => 'Section'],
            ['field' => 'is_publish', 'label' => 'Published', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'photo', 'type' => 'image', 'label' => 'Photo'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'position', 'type' => 'number', 'label' => 'Position'],
            ['name' => 'is_publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'advertisements' => [
        'model' => \App\Models\Advertisement::class,
        'label' => 'Advertisements',
        'permission' => 'advertisement',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'status', 'label' => 'Status'],
            ['field' => 'vendorId', 'label' => 'Vendor'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'vendorId', 'type' => 'text', 'label' => 'Vendor ID'],
            ['name' => 'coverImage', 'type' => 'image', 'label' => 'Cover Image'],
            ['name' => 'status', 'type' => 'text', 'label' => 'Status'],
        ],
    ],
    'vendor-orders' => [
        'model' => \App\Models\VendorOrder::class,
        'view' => 'vendor_orders',
        'route' => 'orders',
        'label' => 'Orders',
        'permission' => 'orders',
        'searchable' => ['status', 'authorID', 'vendorID'],
        'columns' => [
            ['field' => 'id', 'label' => 'Order ID'],
            ['field' => 'status', 'label' => 'Status'],
            ['field' => 'vendorID', 'label' => 'Vendor'],
            ['field' => 'authorID', 'label' => 'Customer'],
            ['field' => 'createdAt', 'label' => 'Date', 'type' => 'datetime'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'rides' => [
        'model' => \App\Models\Ride::class,
        'label' => 'Rides',
        'permission' => 'rides',
        'searchable' => ['status', 'authorID'],
        'columns' => [
            ['field' => 'id', 'label' => 'Ride ID'],
            ['field' => 'status', 'label' => 'Status'],
            ['field' => 'authorID', 'label' => 'Customer'],
            ['field' => 'driverId', 'label' => 'Driver'],
            ['field' => 'createdAt', 'label' => 'Date', 'type' => 'datetime'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'vendors' => [
        'model' => \App\Models\Vendor::class,
        'label' => 'Vendors',
        'permission' => 'vendors',
        'searchable' => ['title', 'phonenumber'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'section_id', 'label' => 'Section'],
            ['field' => 'reststatus', 'label' => 'Open', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'description', 'type' => 'textarea', 'label' => 'Description'],
            ['name' => 'section_id', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'phonenumber', 'type' => 'text', 'label' => 'Phone'],
            ['name' => 'photo', 'type' => 'image', 'label' => 'Photo'],
            ['name' => 'latitude', 'type' => 'number', 'label' => 'Latitude'],
            ['name' => 'longitude', 'type' => 'number', 'label' => 'Longitude'],
            ['name' => 'reststatus', 'type' => 'checkbox', 'label' => 'Restaurant Open'],
        ],
    ],
    'users' => [
        'model' => \App\Models\AppUser::class,
        'table' => 'app_users',
        'label' => 'Customers',
        'permission' => 'users',
        'scope' => 'customers',
        'searchable' => ['firstName', 'lastName', 'email', 'phoneNumber'],
        'columns' => [
            ['field' => 'firstName', 'label' => 'First Name'],
            ['field' => 'lastName', 'label' => 'Last Name'],
            ['field' => 'email', 'label' => 'Email'],
            ['field' => 'phoneNumber', 'label' => 'Phone'],
            ['field' => 'active', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'firstName', 'type' => 'text', 'label' => 'First Name', 'required' => true],
            ['name' => 'lastName', 'type' => 'text', 'label' => 'Last Name'],
            ['name' => 'email', 'type' => 'email', 'label' => 'Email', 'required' => true],
            ['name' => 'phoneNumber', 'type' => 'text', 'label' => 'Phone'],
            ['name' => 'password', 'type' => 'password', 'label' => 'Password'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'active', 'type' => 'checkbox', 'label' => 'Active'],
        ],
    ],
    'zones' => [
        'model' => \App\Models\Zone::class,
        'label' => 'Zones',
        'permission' => 'zone',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'publish', 'label' => 'Published', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'latitude', 'type' => 'number', 'label' => 'Latitude'],
            ['name' => 'longitude', 'type' => 'number', 'label' => 'Longitude'],
            ['name' => 'publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'notifications' => [
        'model' => \App\Models\AppNotification::class,
        'label' => 'Notifications',
        'permission' => 'notification',
        'searchable' => ['subject', 'role'],
        'columns' => [
            ['field' => 'subject', 'label' => 'Subject'],
            ['field' => 'role', 'label' => 'Role'],
        ],
        'form' => [
            ['name' => 'subject', 'type' => 'text', 'label' => 'Subject', 'required' => true],
            ['name' => 'message', 'type' => 'textarea', 'label' => 'Message'],
            ['name' => 'role', 'type' => 'text', 'label' => 'Role'],
        ],
    ],
    'dynamic-notifications' => [
        'model' => \App\Models\DynamicNotification::class,
        'view' => 'dynamic_notifications',
        'route' => 'dynamic-notifications',
        'label' => 'Dynamic Notifications',
        'permission' => 'dynamic-notification',
        'searchable' => ['type', 'subject'],
        'columns' => [
            ['field' => 'type', 'label' => 'Type'],
            ['field' => 'subject', 'label' => 'Subject'],
        ],
        'form' => [
            ['name' => 'type', 'type' => 'text', 'label' => 'Type', 'required' => true],
            ['name' => 'subject', 'type' => 'text', 'label' => 'Subject'],
            ['name' => 'message', 'type' => 'textarea', 'label' => 'Message'],
            ['name' => 'service_type', 'type' => 'text', 'label' => 'Service Type'],
        ],
    ],
    'wallet-transactions' => [
        'model' => \App\Models\WalletTransaction::class,
        'view' => 'wallet_transactions',
        'route' => 'wallet-transactions',
        'label' => 'Wallet Transactions',
        'permission' => 'wallet-transaction',
        'searchable' => ['userId', 'note'],
        'columns' => [
            ['field' => 'userId', 'label' => 'User'],
            ['field' => 'amount', 'label' => 'Amount'],
            ['field' => 'note', 'label' => 'Note'],
            ['field' => 'createdDate', 'label' => 'Date', 'type' => 'datetime'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'parcel-orders' => [
        'model' => \App\Models\ParcelOrder::class,
        'view' => 'parcel_orders',
        'route' => 'parcel-orders',
        'label' => 'Parcel Orders',
        'permission' => 'parcel-order',
        'searchable' => ['status'],
        'columns' => [
            ['field' => 'id', 'label' => 'Order ID'],
            ['field' => 'status', 'label' => 'Status'],
            ['field' => 'authorID', 'label' => 'Customer'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'rental-orders' => [
        'model' => \App\Models\RentalOrder::class,
        'view' => 'rental_orders',
        'route' => 'rental-orders',
        'label' => 'Rental Orders',
        'permission' => 'rental-order',
        'searchable' => ['status'],
        'columns' => [
            ['field' => 'id', 'label' => 'Order ID'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'provider-orders' => [
        'model' => \App\Models\ProviderOrder::class,
        'view' => 'provider_orders',
        'route' => 'provider-orders',
        'label' => 'Provider Orders',
        'permission' => 'provider-order',
        'searchable' => ['status'],
        'columns' => [
            ['field' => 'id', 'label' => 'Order ID'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'payouts' => [
        'model' => \App\Models\Payout::class,
        'label' => 'Payouts',
        'permission' => 'payout',
        'searchable' => ['vendorID'],
        'columns' => [
            ['field' => 'vendorID', 'label' => 'Vendor'],
            ['field' => 'amount', 'label' => 'Amount'],
            ['field' => 'paymentStatus', 'label' => 'Status'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'driver-payouts' => [
        'model' => \App\Models\DriverPayout::class,
        'view' => 'driver_payouts',
        'route' => 'driver-payouts',
        'label' => 'Driver Payouts',
        'permission' => 'driver-payout',
        'searchable' => ['driverID'],
        'columns' => [
            ['field' => 'driverID', 'label' => 'Driver'],
            ['field' => 'amount', 'label' => 'Amount'],
            ['field' => 'paymentStatus', 'label' => 'Status'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'complaints' => [
        'model' => \App\Models\Complaint::class,
        'label' => 'Complaints',
        'permission' => 'complaint',
        'searchable' => ['title', 'status'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title'],
            ['name' => 'description', 'type' => 'textarea', 'label' => 'Description'],
            ['name' => 'status', 'type' => 'text', 'label' => 'Status'],
        ],
    ],
    'sos' => [
        'model' => \App\Models\Sos::class,
        'label' => 'SOS Alerts',
        'permission' => 'sos',
        'searchable' => ['orderId', 'status'],
        'columns' => [
            ['field' => 'orderId', 'label' => 'Order'],
            ['field' => 'status', 'label' => 'Status'],
            ['field' => 'createdAt', 'label' => 'Date', 'type' => 'datetime'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'referrals' => [
        'model' => \App\Models\Referral::class,
        'label' => 'Referrals',
        'permission' => 'referral',
        'searchable' => ['referralCode'],
        'columns' => [
            ['field' => 'referralCode', 'label' => 'Code'],
            ['field' => 'referralBy', 'label' => 'Referrer'],
        ],
        'form' => [
            ['name' => 'referralCode', 'type' => 'text', 'label' => 'Code'],
            ['name' => 'referralBy', 'type' => 'text', 'label' => 'Referrer User ID'],
        ],
    ],
    'stories' => [
        'model' => \App\Models\Story::class,
        'label' => 'Stories',
        'permission' => 'story',
        'searchable' => ['vendorID'],
        'columns' => [
            ['field' => 'vendorID', 'label' => 'Vendor'],
            ['field' => 'createdAt', 'label' => 'Date', 'type' => 'datetime'],
        ],
        'form' => [
            ['name' => 'vendorID', 'type' => 'text', 'label' => 'Vendor ID'],
            ['name' => 'videoUrl', 'type' => 'text', 'label' => 'Video URL'],
            ['name' => 'sectionID', 'type' => 'text', 'label' => 'Section ID'],
        ],
    ],
    'email-templates' => [
        'model' => \App\Models\EmailTemplate::class,
        'view' => 'email_templates',
        'route' => 'email-templates',
        'label' => 'Email Templates',
        'permission' => 'email-template',
        'searchable' => ['type', 'subject'],
        'columns' => [
            ['field' => 'type', 'label' => 'Type'],
            ['field' => 'subject', 'label' => 'Subject'],
        ],
        'form' => [
            ['name' => 'type', 'type' => 'text', 'label' => 'Type', 'required' => true],
            ['name' => 'subject', 'type' => 'text', 'label' => 'Subject'],
            ['name' => 'message', 'type' => 'textarea', 'label' => 'Message'],
        ],
    ],
    'vendor-products' => [
        'model' => \App\Models\VendorProduct::class,
        'view' => 'vendor_products',
        'route' => 'vendor-products',
        'label' => 'Products',
        'permission' => 'items',
        'searchable' => ['name', 'description'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'price', 'label' => 'Price'],
            ['field' => 'vendorID', 'label' => 'Vendor'],
            ['field' => 'publish', 'label' => 'Published', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'description', 'type' => 'textarea', 'label' => 'Description'],
            ['name' => 'price', 'type' => 'number', 'label' => 'Price'],
            ['name' => 'vendorID', 'type' => 'text', 'label' => 'Vendor ID'],
            ['name' => 'categoryID', 'type' => 'text', 'label' => 'Category ID'],
            ['name' => 'photo', 'type' => 'image', 'label' => 'Photo'],
            ['name' => 'publish', 'type' => 'checkbox', 'label' => 'Published'],
        ],
    ],
    'provider-categories' => [
        'model' => \App\Models\ProviderCategory::class,
        'view' => 'provider_categories',
        'route' => 'provider-categories',
        'label' => 'Provider Categories',
        'permission' => 'provider-category',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'sectionId', 'label' => 'Section'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'parentCategoryId', 'type' => 'text', 'label' => 'Parent Category'],
            ['name' => 'image', 'type' => 'image', 'label' => 'Image'],
        ],
    ],
    'provider-services' => [
        'model' => \App\Models\ProviderService::class,
        'view' => 'providers_services',
        'route' => 'provider-services',
        'label' => 'Provider Services',
        'permission' => 'provider-service',
        'searchable' => ['title'],
        'columns' => [
            ['field' => 'title', 'label' => 'Title'],
            ['field' => 'price', 'label' => 'Price'],
            ['field' => 'sectionId', 'label' => 'Section'],
        ],
        'form' => [
            ['name' => 'title', 'type' => 'text', 'label' => 'Title', 'required' => true],
            ['name' => 'price', 'type' => 'number', 'label' => 'Price'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
            ['name' => 'categoryId', 'type' => 'text', 'label' => 'Category ID'],
        ],
    ],
    'provider-workers' => [
        'model' => \App\Models\ProviderWorker::class,
        'view' => 'providers_workers',
        'route' => 'provider-workers',
        'label' => 'Provider Workers',
        'permission' => 'provider-worker',
        'searchable' => ['firstName', 'lastName'],
        'columns' => [
            ['field' => 'firstName', 'label' => 'First Name'],
            ['field' => 'lastName', 'label' => 'Last Name'],
            ['field' => 'providerId', 'label' => 'Provider'],
        ],
        'form' => [
            ['name' => 'firstName', 'type' => 'text', 'label' => 'First Name', 'required' => true],
            ['name' => 'lastName', 'type' => 'text', 'label' => 'Last Name'],
            ['name' => 'providerId', 'type' => 'text', 'label' => 'Provider ID'],
            ['name' => 'profilePictureURL', 'type' => 'image', 'label' => 'Photo'],
        ],
    ],
    'subscription-histories' => [
        'model' => \App\Models\SubscriptionHistory::class,
        'view' => 'subscription_histories',
        'route' => 'subscription-histories',
        'label' => 'Subscription History',
        'permission' => 'subscription-history',
        'searchable' => ['user_id'],
        'columns' => [
            ['field' => 'user_id', 'label' => 'User'],
            ['field' => 'expiry_date', 'label' => 'Expiry', 'type' => 'datetime'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'booked-tables' => [
        'model' => \App\Models\BookedTable::class,
        'view' => 'booked_tables',
        'route' => 'booked-tables',
        'label' => 'Table Bookings',
        'permission' => 'book-table',
        'searchable' => ['status'],
        'columns' => [
            ['field' => 'vendorID', 'label' => 'Vendor'],
            ['field' => 'authorID', 'label' => 'Customer'],
            ['field' => 'status', 'label' => 'Status'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'item-reviews' => [
        'model' => \App\Models\ItemReview::class,
        'view' => 'items_reviews',
        'route' => 'item-reviews',
        'label' => 'Item Reviews',
        'permission' => 'review',
        'searchable' => ['comment'],
        'columns' => [
            ['field' => 'productId', 'label' => 'Product'],
            ['field' => 'rating', 'label' => 'Rating'],
            ['field' => 'comment', 'label' => 'Comment'],
        ],
        'form' => [],
        'readonly' => true,
    ],
    'promos' => [
        'model' => \App\Models\Promo::class,
        'label' => 'Promos',
        'permission' => 'cab-promo',
        'searchable' => ['code'],
        'columns' => [
            ['field' => 'code', 'label' => 'Code'],
            ['field' => 'discount', 'label' => 'Discount'],
        ],
        'form' => [
            ['name' => 'code', 'type' => 'text', 'label' => 'Code', 'required' => true],
            ['name' => 'discount', 'type' => 'number', 'label' => 'Discount'],
            ['name' => 'sectionId', 'type' => 'text', 'label' => 'Section ID'],
        ],
    ],
    'car-makes' => [
        'model' => \App\Models\CarMake::class,
        'view' => 'car_makes',
        'route' => 'car-makes',
        'label' => 'Car Makes',
        'permission' => 'make',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'isActive', 'label' => 'Active', 'type' => 'boolean'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'isActive', 'type' => 'checkbox', 'label' => 'Active'],
        ],
    ],
    'car-models' => [
        'model' => \App\Models\CarModel::class,
        'view' => 'car_models',
        'route' => 'car-models',
        'label' => 'Car Models',
        'permission' => 'model',
        'searchable' => ['name'],
        'columns' => [
            ['field' => 'name', 'label' => 'Name'],
            ['field' => 'car_make_id', 'label' => 'Make ID'],
        ],
        'form' => [
            ['name' => 'name', 'type' => 'text', 'label' => 'Name', 'required' => true],
            ['name' => 'car_make_id', 'type' => 'text', 'label' => 'Car Make ID'],
            ['name' => 'isActive', 'type' => 'checkbox', 'label' => 'Active'],
        ],
    ],
];
