<?php

/**
 * Collection → MySQL table mapping for KWEEK platform.
 * Document IDs are preserved as string primary keys (max 64 chars).
 */
return [
    'SOS' => ['table' => 'sos', 'model' => \App\Models\Sos::class],
    'advertisements' => ['table' => 'advertisements', 'model' => \App\Models\Advertisement::class],
    'banner_items' => ['table' => 'banner_items', 'model' => \App\Models\BannerItem::class],
    'booked_table' => ['table' => 'booked_tables', 'model' => \App\Models\BookedTable::class],
    'brands' => ['table' => 'brands', 'model' => \App\Models\Brand::class],
    'car_make' => ['table' => 'car_makes', 'model' => \App\Models\CarMake::class],
    'car_model' => ['table' => 'car_models', 'model' => \App\Models\CarModel::class],
    'chat_admin' => ['table' => 'chat_admin', 'model' => \App\Models\ChatAdmin::class],
    'chat_driver' => ['table' => 'chat_driver', 'model' => \App\Models\ChatDriver::class],
    'chat_provider' => ['table' => 'chat_provider', 'model' => \App\Models\ChatProvider::class],
    'chat_store' => ['table' => 'chat_store', 'model' => \App\Models\ChatStore::class],
    'chat_worker' => ['table' => 'chat_worker', 'model' => \App\Models\ChatWorker::class],
    'cms_pages' => ['table' => 'cms_pages', 'model' => \App\Models\CmsPage::class],
    'complaints' => ['table' => 'complaints', 'model' => \App\Models\Complaint::class],
    'coupons' => ['table' => 'coupons', 'model' => \App\Models\Coupon::class],
    'currencies' => ['table' => 'currencies', 'model' => \App\Models\Currency::class],
    'documents' => ['table' => 'documents', 'model' => \App\Models\Document::class],
    'documents_verify' => ['table' => 'documents_verify', 'model' => \App\Models\DocumentVerify::class],
    'driver_payouts' => ['table' => 'driver_payouts', 'model' => \App\Models\DriverPayout::class],
    'dynamic_notification' => ['table' => 'dynamic_notifications', 'model' => \App\Models\DynamicNotification::class],
    'email_templates' => ['table' => 'email_templates', 'model' => \App\Models\EmailTemplate::class],
    'favorite_item' => ['table' => 'favorite_items', 'model' => \App\Models\FavoriteItem::class],
    'favorite_provider' => ['table' => 'favorite_providers', 'model' => \App\Models\FavoriteProvider::class],
    'favorite_service' => ['table' => 'favorite_services', 'model' => \App\Models\FavoriteService::class],
    'favorite_vendor' => ['table' => 'favorite_vendors', 'model' => \App\Models\FavoriteVendor::class],
    'gift_cards' => ['table' => 'gift_cards', 'model' => \App\Models\GiftCard::class],
    'gift_purchases' => ['table' => 'gift_purchases', 'model' => \App\Models\GiftPurchase::class],
    'items_review' => ['table' => 'items_reviews', 'model' => \App\Models\ItemReview::class],
    'notifications' => ['table' => 'notifications', 'model' => \App\Models\AppNotification::class],
    'on_boarding' => ['table' => 'on_boarding', 'model' => \App\Models\OnBoarding::class],
    'order_transactions' => ['table' => 'order_transactions', 'model' => \App\Models\OrderTransaction::class],
    'parcel_categories' => ['table' => 'parcel_categories', 'model' => \App\Models\ParcelCategory::class],
    'parcel_coupons' => ['table' => 'parcel_coupons', 'model' => \App\Models\ParcelCoupon::class],
    'parcel_orders' => ['table' => 'parcel_orders', 'model' => \App\Models\ParcelOrder::class],
    'parcel_weight' => ['table' => 'parcel_weights', 'model' => \App\Models\ParcelWeight::class],
    'payouts' => ['table' => 'payouts', 'model' => \App\Models\Payout::class],
    'popular_destinations' => ['table' => 'popular_destinations', 'model' => \App\Models\PopularDestination::class],
    'promos' => ['table' => 'promos', 'model' => \App\Models\Promo::class],
    'provider_categories' => ['table' => 'provider_categories', 'model' => \App\Models\ProviderCategory::class],
    'provider_orders' => ['table' => 'provider_orders', 'model' => \App\Models\ProviderOrder::class],
    'providers_coupons' => ['table' => 'providers_coupons', 'model' => \App\Models\ProviderCoupon::class],
    'providers_services' => ['table' => 'providers_services', 'model' => \App\Models\ProviderService::class],
    'providers_workers' => ['table' => 'providers_workers', 'model' => \App\Models\ProviderWorker::class],
    'rating' => ['table' => 'ratings', 'model' => \App\Models\Rating::class],
    'referral' => ['table' => 'referrals', 'model' => \App\Models\Referral::class],
    'rental_coupons' => ['table' => 'rental_coupons', 'model' => \App\Models\RentalCoupon::class],
    'rental_orders' => ['table' => 'rental_orders', 'model' => \App\Models\RentalOrder::class],
    'rental_packages' => ['table' => 'rental_packages', 'model' => \App\Models\RentalPackage::class],
    'rental_vehicle_type' => ['table' => 'rental_vehicle_types', 'model' => \App\Models\RentalVehicleType::class],
    'review_attributes' => ['table' => 'review_attributes', 'model' => \App\Models\ReviewAttribute::class],
    'rides' => ['table' => 'rides', 'model' => \App\Models\Ride::class],
    'sections' => ['table' => 'sections', 'model' => \App\Models\Section::class],
    'services' => ['table' => 'services', 'model' => \App\Models\Service::class],
    'settings' => ['table' => 'settings', 'model' => \App\Models\Setting::class],
    'story' => ['table' => 'stories', 'model' => \App\Models\Story::class],
    'subscription_history' => ['table' => 'subscription_histories', 'model' => \App\Models\SubscriptionHistory::class],
    'subscription_plans' => ['table' => 'subscription_plans', 'model' => \App\Models\SubscriptionPlan::class],
    'tax' => ['table' => 'taxes', 'model' => \App\Models\Tax::class],
    'users' => ['table' => 'app_users', 'model' => \App\Models\AppUser::class],
    'vehicle_type' => ['table' => 'vehicle_types', 'model' => \App\Models\VehicleType::class],
    'vendor_attributes' => ['table' => 'vendor_attributes', 'model' => \App\Models\VendorAttribute::class],
    'vendor_filters' => ['table' => 'vendor_filters', 'model' => \App\Models\VendorFilter::class],
    'vendor_categories' => ['table' => 'vendor_categories', 'model' => \App\Models\VendorCategory::class],
    'vendor_orders' => ['table' => 'vendor_orders', 'model' => \App\Models\VendorOrder::class],
    'vendor_products' => ['table' => 'vendor_products', 'model' => \App\Models\VendorProduct::class],
    'vendors' => ['table' => 'vendors', 'model' => \App\Models\Vendor::class],
    'wallet' => ['table' => 'wallet', 'model' => \App\Models\Wallet::class],
    'wallet_transaction' => ['table' => 'wallet_transactions', 'model' => \App\Models\WalletTransaction::class],
    'withdraw_method' => ['table' => 'withdraw_methods', 'model' => \App\Models\WithdrawMethod::class],
    'zone' => ['table' => 'zones', 'model' => \App\Models\Zone::class],
    'arropay_disbursement_withdrawals' => ['table' => 'arropay_disbursement_withdrawals'],
    'arropay_v2_payments' => ['table' => 'arropay_v2_payments'],
];
